/** Product catalog synced with Product Listing - Sheet1.csv */
export const catalogProducts = [
  {
    name: "Black Boot",
    slug: "black-boot",
    color: "Black",
    color_hex: "#111111",
    gender: "men" as const,
    style: "Boot",
    material: "Premium Leather",
    hardware: "Elastic side gusset with pull tab",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Black boot with a structured silhouette, polished leather finish, and everyday versatility.",
    images: ["catalog-extra/black-boot-2.png", "catalog-extra/black-boot-1.png", "catalog-extra/black-boot-3.png"],
    is_featured: true,
    supported_types: ["covered"] as const,
    highlights: [
      "Structured black leather boot with a clean side profile",
      "Elastic gusset entry with reinforced heel pull tab",
      "Finished for daily wear with Velcraft quality standards",
    ],
  },
  {
    name: "Brown Boot",
    slug: "brown-boot",
    color: "Brown",
    color_hex: "#6B4423",
    gender: "men" as const,
    style: "Boot",
    material: "Premium Leather",
    hardware: "Elastic side gusset with pull tab",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Brown boot crafted in a rich leather tone with a refined, versatile profile.",
    images: ["catalog-extra/brown-boot-1.png", "catalog-extra/brown-boot-2.png", "catalog-extra/brown-boot-3.png"],
    is_featured: true,
    supported_types: ["covered"] as const,
    highlights: [
      "Warm brown leather upper with a classic boot silhouette",
      "Comfort-focused gusset construction for easy wear",
      "Pairs easily with formal and smart-casual looks",
    ],
  },
  {
    name: "Dark Blue Covered",
    slug: "dark-blue-covered",
    color: "Dark Blue",
    color_hex: "#1B2A41",
    style: "Covered Mule",
    material: "Velvet",
    hardware: "Silver horsebit detail",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Dark blue covered mule in velvet with a polished horsebit finish.",
    images: [
      "catalog-extra/blue-covered-2.png",
      "catalog-extra/blue-covered-1.png",
      "catalog-extra/blue-covered-3.png",
      "catalog-extra/blue-covered-4.png",
    ],
    is_featured: true,
    supported_types: ["covered"] as const,
    highlights: [
      "Deep navy velvet upper with a sleek covered profile",
      "Signature metal horsebit hardware across the vamp",
      "Statement mule designed for elevated everyday dressing",
    ],
  },
  {
    name: "Black Covered",
    slug: "black-covered",
    color: "Black",
    color_hex: "#111111",
    style: "Covered Mule",
    material: "Suede",
    hardware: "Gold horsebit detail",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Classic black covered mule with a minimal silhouette and gold hardware.",
    images: [
      "noir-minimal-mule/black-covered-2.png",
      "noir-minimal-mule/black-covered-1.png",
      "noir-minimal-mule/black-covered-3.png",
    ],
    is_featured: true,
    supported_types: ["covered"] as const,
    highlights: [
      "Black suede covered mule with a sharp, minimal shape",
      "Gold horsebit accent for a classic luxury finish",
      "Easy day-to-night styling in a timeless color",
    ],
  },
  {
    name: "Medium Brown Covered",
    slug: "medium-brown-covered",
    color: "Coffee Brown",
    color_hex: "#6F4E37",
    style: "Covered Mule",
    material: "Suede",
    hardware: "Gold horsebit detail",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Coffee brown covered mule with warm tones and soft suede texture.",
    images: [
      "espresso-horsebit-mule/medium-brown-covered-1.png",
      "espresso-horsebit-mule/medium-brown-covered-2.png",
      "espresso-horsebit-mule/medium-brown-covered-3.png",
    ],
    is_featured: false,
    supported_types: ["covered"] as const,
    highlights: [
      "Coffee brown suede with a rich, warm finish",
      "Covered mule profile with signature horsebit hardware",
      "Neutral tone suited to year-round styling",
    ],
  },
  {
    name: "Brown Covered",
    slug: "brown-covered",
    color: "Medium Brown",
    color_hex: "#A67B5B",
    style: "Covered Mule",
    material: "Suede",
    hardware: "Gold horsebit detail",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Medium brown covered mule with a soft suede finish and natural tone.",
    images: [
      "camel-suede-mule/brown-covered-1.png",
      "camel-suede-mule/brown-covered-2.png",
      "camel-suede-mule/brown-covered-3.png",
    ],
    is_featured: false,
    supported_types: ["covered"] as const,
    highlights: [
      "Medium brown suede upper with a relaxed luxury feel",
      "Gold horsebit detail on a classic covered silhouette",
      "Natural earthy tone for versatile outfit pairing",
    ],
  },
  {
    name: "Brown Diff Buckle",
    slug: "brown-diff-buckle",
    color: "Dark Brown",
    color_hex: "#3D2B1F",
    style: "Signature Mule",
    material: "Suede",
    hardware: "Heritage square buckle",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Dark brown mule featuring a distinctive heritage buckle detail.",
    images: [
      "espresso-horsebit-mule/brown-diff-buckle-1.png",
      "espresso-horsebit-mule/brown-diff-buckle-2.png",
    ],
    is_featured: false,
    supported_types: ["backless", "covered"] as const,
    highlights: [
      "Dark brown suede with a statement heritage buckle",
      "Available in covered and backless styling options",
      "Designed for customers who want a bolder hardware look",
    ],
  },
  {
    name: "Dark Brown Covered",
    slug: "dark-brown-covered",
    color: "Dark Brown",
    color_hex: "#3D2B1F",
    style: "Covered Mule",
    material: "Suede",
    hardware: "Gold horsebit detail",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Dark brown covered mule with deep coloring and a refined profile.",
    images: [
      "espresso-horsebit-mule/dark-brown-covered-1.png",
      "espresso-horsebit-mule/dark-brown-covered-2.png",
      "espresso-horsebit-mule/dark-brown-covered-3.png",
    ],
    is_featured: false,
    supported_types: ["covered"] as const,
    highlights: [
      "Deep dark brown suede with a polished covered shape",
      "Gold horsebit hardware for a classic Velcraft finish",
      "Sophisticated tone for formal and evening wear",
    ],
  },
  {
    name: "Charcoal",
    slug: "charcoal",
    color: "Charcoal",
    color_hex: "#36454F",
    style: "Covered Mule",
    material: "Suede",
    hardware: "Gold horsebit detail",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Charcoal mule with a muted modern tone and covered silhouette.",
    images: ["espresso-horsebit-mule/charcoal-1.png", "espresso-horsebit-mule/charcoal-2.png"],
    is_featured: false,
    supported_types: ["covered"] as const,
    highlights: [
      "Charcoal suede finish with a contemporary muted tone",
      "Covered mule profile with gold horsebit detail",
      "Modern neutral shade for minimalist wardrobes",
    ],
  },
  {
    name: "Faune",
    slug: "faune",
    color: "Faune",
    color_hex: "#C4A882",
    style: "Covered Mule",
    material: "Suede",
    hardware: "Gold horsebit detail",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Faune-colored mule with a soft neutral palette and covered finish.",
    images: ["catalog-extra/faune-3.png", "ivory-gold-bit-mule/faune-1.png", "catalog-extra/faune-2.png"],
    is_featured: false,
    supported_types: ["covered"] as const,
    highlights: [
      "Soft faune suede tone with a light, elegant finish",
      "Covered mule shape with signature gold hardware",
      "Neutral shade that works across seasons",
    ],
  },
  {
    name: "Grey",
    slug: "grey",
    color: "Grey",
    color_hex: "#8B8680",
    style: "Covered Mule",
    material: "Suede",
    hardware: "Gold horsebit detail",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Grey mule with understated elegance and a versatile covered profile.",
    images: ["catalog-extra/grey.png", "catalog-extra/grey-2.png", "catalog-extra/grey-3.png"],
    is_featured: false,
    supported_types: ["covered"] as const,
    highlights: [
      "Grey suede upper with a clean covered silhouette",
      "Gold horsebit hardware for a refined finish",
      "Understated color for everyday luxury styling",
    ],
  },
  {
    name: "Full Black Backless",
    slug: "full-black-backless",
    color: "Black",
    color_hex: "#111111",
    style: "Backless Mule",
    material: "Suede",
    hardware: "Open back heel",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Full black backless mule with an open heel and minimal profile.",
    images: [
      "noir-minimal-mule/full-back-backless-1.png",
      "noir-minimal-mule/full-black-backless-2.png",
    ],
    is_featured: false,
    supported_types: ["backless"] as const,
    highlights: [
      "Black suede backless mule with an open heel design",
      "Lightweight slip-on feel with a sleek profile",
      "Ideal for warm weather and effortless styling",
    ],
  },
  {
    name: "Black and White Backless",
    slug: "black-and-white-backless",
    color: "Black & White",
    color_hex: "#111111",
    style: "Backless Mule",
    material: "Suede",
    hardware: "Contrast trim detail",
    sizing: "EU 40–45 Men",
    base_price: 2999,
    description: "Black and white backless mule with bold contrast detailing.",
    images: [
      "noir-minimal-mule/black-and-white-backless-1.png",
      "noir-minimal-mule/black-and-white-backless-2.png",
    ],
    is_featured: false,
    supported_types: ["backless"] as const,
    highlights: [
      "Black and white contrast finish on a backless mule",
      "Open heel silhouette for easy slip-on wear",
      "Bold two-tone look for statement styling",
    ],
  },
  {
    name: "Black XL",
    slug: "black-xl",
    color: "Black",
    color_hex: "#111111",
    style: "XL Backless Mule",
    material: "Premium Leather",
    hardware: "Extended fit profile",
    sizing: "XL fit · EU 40–45 Men",
    base_price: 4500,
    description: "Black XL backless mule with an extended fit profile and premium finish.",
    images: ["catalog-extra/black-boot-1.png"],
    is_featured: false,
    supported_types: ["backless"] as const,
    highlights: [
      "Black XL backless mule with an extended fit profile",
      "Premium leather construction for larger sizing needs",
      "Designed for customers requiring additional room and comfort",
    ],
  },
  {
    name: "Brown XL",
    slug: "brown-xl",
    color: "Brown",
    color_hex: "#6B4423",
    style: "XL Backless Mule",
    material: "Premium Leather",
    hardware: "Extended fit profile",
    sizing: "XL fit · EU 40–45 Men",
    base_price: 4500,
    description: "Brown XL backless mule with an extended fit profile and rich leather tone.",
    images: ["catalog-extra/brown-boot-1.png"],
    is_featured: false,
    supported_types: ["backless"] as const,
    highlights: [
      "Brown XL backless mule with an extended fit profile",
      "Premium leather upper in a rich brown tone",
      "XL sizing option for enhanced comfort and coverage",
    ],
  },
] as const;

export function catalogThumbnailPath(slug: string) {
  const product = catalogProducts.find((entry) => entry.slug === slug);
  if (product?.images[0]) {
    return `/images/shoes/${product.images[0]}`;
  }

  return `/images/shoes/${slug}/main.png`;
}

export function catalogGalleryPaths(slug: string) {
  const product = catalogProducts.find((entry) => entry.slug === slug);
  if (!product) {
    return [catalogThumbnailPath(slug)];
  }

  const imagePaths = product.images.map((image) => `/images/shoes/${image}`);
  return [...new Set(imagePaths)];
}
